import { useRef } from 'react';
import Head from 'next/head';
import gsap from 'gsap/dist/gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';

import useIsomorphicLayoutEffect from '../helpers/isomorphicEffect';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

export default function Home() {
  const main = useRef();
  const videoRef = useRef();

  useIsomorphicLayoutEffect(() => {
    const ctx = gsap.context(() => {
      let tl = gsap.timeline({
        scrollTrigger: {
          trigger: 'video',
          start: 'top top',
          end: 'bottom+=200% bottom',
          scrub: 2,
          markers: true,
        },
      });
      videoRef.current.onloadedmetadata = function () {
        tl.to(videoRef.current, {
          currentTime: videoRef.current.duration,
          ease: 'none',
        });
      };
    }, main);
    // Dealing with devices
    function isTouchDevice() {
      return 'ontouchstart' in window || navigator.maxTouchPoints > 0;
    }
    if (isTouchDevice()) {
      console.log('rodou FN');

      videoRef.current.setNativeProps({ paused: true });
      videoRef.current.setNativeProps({ paused: false });
    }
    return () => ctx.revert();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main" ref={main}>
        <video
          ref={videoRef}
          className="video"
          playsInline={true}
          webkit-playsinline="true"
          preload="auto"
          muted
        >
          <source
            src="https://www.dropbox.com/s/ob3iz14tgo29qns/Abstract%20-%2020072_960.mp4?raw=1"
            type="video/mp4"
          />
        </video>
      </main>
    </>
  );
}
